postgres:
  restart: always
  image: postgres:latest
  expose:
    - "5432"
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data
